-- Add new donation category enum values
ALTER TYPE "DonationCategory" ADD VALUE IF NOT EXISTS 'SPECIAL_EVENT';
ALTER TYPE "DonationCategory" ADD VALUE IF NOT EXISTS 'MOSQUE_MAINTENANCE';
ALTER TYPE "DonationCategory" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_DUES';
ALTER TYPE "DonationCategory" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION';
